### PR TITLE
Support new version of Google Pinyin Input Method.

### PR DESCRIPTION
**Pull request by Gh0u1L5**

### CODE REVIEW

**Comment by mosaic-greg** [comment]
Hi this looks great, is there an apk available please?

**Comment by dheera** [comment]
Whoops for some reason I didn't see this comment! I'll try to review the pull request in the next couple of days.

**Comment by Gh0u1L5** [comment]
@mosaic-greg Oops, my fault. I just compiled an apk, feel free to use it.

**Comment by Gh0u1L5** [comment]
@dheera Lol sure, no worries, after all I no longer expected to get any response.

**Comment by Gh0u1L5** [comment]
@dheera btw, the apk I compiled hasn't been signed yet, could you please sign it?

**Comment by mosaic-greg** [comment]
Hi i've downloaded the apk, when I try to install it android says it's corrupt, is that because it's not signed? @dheera

**Pull request closed without merging**
